### ISSUE TITLE
Curious how this compares to clojure-jna?

### ISSUE THREAD

**Issue by didibus** [techascent/tech.jna#3]
Curious how this compares to [clojure-jna](https://github.com/Chouser/clojure-jna)?

**Comment by cnuernber** [comment]
And another interesting library: [clj-native](https://github.com/bagucode/clj-native).

And how does jna compare to [jnr](https://github.com/jnr/jnr-ffi).

There are lots of options in this space.

In general I was looking for a declarative syntax that includes coercive pathways.  And I need to change which library a given namespace is bound to dynamically.  

For instance here are the [python c bindings](https://github.com/clj-python/libpython-clj/blob/master/src/libpython_clj/jna/protocols/object.clj#L65).  Note that the system finds the python shared library dynamically on startup so all of these calls are dynamically bound.  There is a lookup pathway for libraries and logs exactly what failed and where it looked for libraries and much deeper bindings to lots of JNA functionality both here and deep within the datatype library's various internal pathways.  [Copying a java array to a pointer](https://github.com/techascent/tech.datatype/blob/master/src/tech/v2/datatype/fast_copy.clj#L254), for instance. 

Chouser doesn't appear to be maintaining this library any more; it has not been touched since 2014.  

As a broad comparison I would say this library is actively maintained and is just a more in-depth, batteries-included approach to binding to native libraries.

**Comment by didibus** [comment]
Cool, I think this answers my question mostly.

Any words related to performance? Like overhead? Does it all end up the same since its JNA under the hood?

**Comment by cnuernber** [comment]
It's all the same.  If you are patient you can use direct mapping and that is quite a lot faster i guess comparable to jnr then.  But you have to at that point generate a concrete class.  We wrote an article (functions across languages) that details how the non-direct-mapped pathway works.

**Comment by cnuernber** [comment]
@didibus - I now do have something markedly better - [dtype-next's ffi interface](https://cnuernber.github.io/dtype-next/tech.v3.datatype.ffi.html).  I use this in libpython-clj2 to get 32 bit support *and* support for jdk-16 who's FFI pathway is markedly faster than JNA or JNR direct mapping be damned :-).  Something to think about :-).
